### ISSUE TITLE
better documentation

### ISSUE THREAD

**Issue by TadusPro** [halesyy/fame-adder#1]
pls add better documentation how to use, I dont understand how its working its just seting the mouse att random posisiton?

**Comment by halesyy** [comment]
Sure, I'll add some more documentation this afternoon that better explains the purpose. It's meant to sit over the top of Snapchat on a Teamviewer connection to a fully-useable phone, then hit enter in the adding area of Snapchat and the mouse moves and changes to run the process of adding people automatically pulled from the API listed.

**Comment by halesyy** [comment]
How is that? I added more documentation including screenshots and placement requirements, but I also have a video at https://www.youtube.com/watch?v=VyrM7s6q_NI which explains it in video format. Has a different approach than the entire technical side, though.
